### ISSUE TITLE
what is the structure of the site we need for launch (i.e. what pages do we need?) 

### ISSUE THREAD

**Issue by sinker** [OpenNews/srccon#20]
ANSWER FROM KISSANE: 
the answer to this is that we need to figure out how we are handling archives. I am very much in favor of moving the entirety of the *current state* of the 2014 site into 2014.srccon.org (and perhaps 2014schedule.srccon.org), both because archiving is just good practice and because we will want to refer to things from last year. Assuming that this is true, here's what I sketched for launch:

Option one: 
* Homepage only, listing event dates, city, venue, hotel, ticket price, and upcoming calendar stuff (proposals open on ____)
 * Plus archive we can link to as needed
 * Plus current footer info, minus sponsor lists and links 

Option two:
* Homepage: event dates, city
* Registration (or maybe just Tickets): ticket price, on-sale dates, mention of scholarships
* Location: City, venue, hotel, neighborhood description lite
* Sessions: Light description of session style, link to last year's schedule, opening date for proposals 
 * Plus archive we can link to as needed
 * Plus current footer info, minus sponsor lists and links 

I think we should go with option 2—or, more likely, a minor variant of it after we figure out what obvious things I'm forgetting.

**Comment by sinker** [comment]
ARCHIVES: we can very easily create an archive. the easiest way is to create a repo `2014srccon` or whatever and then manage the 2014 subdomain at the CNAME level. Ditto for schedule.

**Comment by sinker** [comment]
I think Option two is the best, as it already sets up about 90% of the overall site structure we'll stick with, instead of adding new things over the next couple months.

**Comment by kissane** [comment]
Yeah, that's my thought too, about the site structure. And I'm pretty pro offering more information rather than less when asking people to plan travel.

**Comment by sinker** [comment]
OK, so I've created a directory called "parkinglot" so that all the various pages we will need, post launch, exist

**Comment by sinker** [comment]
OK, with #26 the site structure of srccon2015 branch should reflect the Option Two above.

**Comment by sinker** [comment]
Closing.
