### ISSUE TITLE
the bullets on <ul>s are slightly offscreen on narrow browsers

### ISSUE THREAD

**Issue by benlk** [OpenNews/srccon#206]
A very minor CSS problem, seen on https://srccon.org/logistics/ in Chrome 59 on OSX.

This was seen between browser widths from ~830 to 800px.

<img width="129" alt="screen shot 2017-07-07 at 4 44 16 pm" src="https://user-images.githubusercontent.com/1754187/27976279-d0cca97a-6333-11e7-8763-1644da606e80.png">

**Comment by ryanpitts** [comment]
we revised the site design this year, so I think this one's handled. Thanks!

**Comment by benlk** [comment]
Yep, based on https://srccon.org/participation/ it is now fixed.
