### ISSUE TITLE
what pages need new photos? 

### ISSUE THREAD

**Issue by sinker** [OpenNews/srccon#21]
ANSWER FROM KISSANE: 
Assuming a variation on option 2, Home, Registration, Location, and Sessions (and I've started collecting photos, too)

**Comment by sinker** [comment]
@kissane do you have a link to where you're collecting photos?

**Comment by kissane** [comment]
TABS. I have them in TABS. Hang on.

**Comment by kissane** [comment]
I thought I had more up, but I may have to look through my browser history on my other machine. Here's what I have here:

https://www.flickr.com/photos/alles-banane/5615986630
https://www.flickr.com/photos/enjoyfatty/158320782
https://www.flickr.com/photos/jpellgen/3951843868
https://www.flickr.com/photos/dannylankford/3616140995

**Comment by sinker** [comment]
OK great. Let's just continue to collect them here.

**Comment by sinker** [comment]
I have found: 
https://www.flickr.com/photos/onepointfour/6481720265/sizes/l <-- minneapolis skyline, night
https://www.flickr.com/photos/stonebridgedapper/3862726485/sizes/l <-- mcnamera center, exterior

**Comment by kissane** [comment]
That photo of the center is copyrighted, but I love the skyline one.

**Comment by kissane** [comment]
Can we close this one now, @sinker?

**Comment by sinker** [comment]
this is closed.
