### ISSUE TITLE
    beyond the obvious pages/images/etc are any major redesign needs/feels for the site (i.e. where nav is, logo space is too big, or should be adjusted on scroll or ?? etc) 

### ISSUE THREAD

**Issue by sinker** [OpenNews/srccon#22]
ANSWER FROM KISSANE: 

I have a lot of feels, I'm afraid. But that's great, because it means we're not on such a panicky schedule!

* I would love to tighten up the screen space that goes to images on the subpages just a bit, we need to do an audit of type and headers, and the nav could use a design polish—type details, things like that. Otherwise, my only thing is that the homepage should be its own thing, and should not be designed around a lot of body text to the same degree as the subpages. (Like, the current state of the SRCCON homepage feels way too short, because the page design wants more text in the middle, I think, to feel balanced.) 
* Not to say this is the model, but http://confabevents.com/events/central has the kind of homepage weight I think would be great for us—the homepage is a poster, a stylish intro, and an easy in to all the information. 
* In general, I think we can find ways to make the little touches in the design feel polished, but I haven't gone through with that level of care yet.
* We should make the schedule match the site this time around.

**Comment by sinker** [comment]
yes, I agree that the homepage has always felt a little iffy. I like the "poster" concept: just something simple, straightforward, says what it is minimally and pushes to the important stuff. 

I actually like the [XOXO site](http://2014.xoxofest.com/) for its poster-ish feel (really like the single-sentence description + date right front and center) but especially how the same general feel transfers to the detail pages, but isntead of retaining the big logo, etc, that space is devoted to the actual page title + micro description or whatever.

**Comment by kissane** [comment]
Yes! That's a beautiful example.

**Comment by sinker** [comment]
I would be very happy aping XOXO's general approach, which would mean:
* Home page needs a 1 sentence (realistically like under 10 word) description of SRCCON.
* Any other page needs a little lengthier one-sentence description of that page's topic (see: http://2014.xoxofest.com/conference/ for an example)

**Comment by kissane** [comment]
Awesome. On it. (Well, on it this evening, if not before.)

**Comment by sinker** [comment]
here's first pass on addressing these issues. This is just a sample page--all CSS is in the page itself right now--until we've got it looking/working the way it should: 

http://srccon.org/testing/

**Comment by sinker** [comment]
and a homepage sketch, going for the more "poster" feeling you mentioned @kissane: http://srccon.org/testing/homepage.html

**Comment by sinker** [comment]
the homepage text is 100% temped in, obvs

**Comment by kissane** [comment]
Couple of small things:

* The blurb in the header may need a box behind it with like 20-30% opacity to make the text more readable, but maybe note
* The sponsors section feels like it needs a color band or something to set it off from the rest of the page
* I love ALLLLLLL the type except I have the slightest itch about the subpage header in bold ("Sessions") at that size. Not sure why, it just feels a little rounder and cartoonier than all the other type? Mild feels, but feels.

**Comment by kissane** [comment]
@sinker Noting here until it's time to split it into a dedicated issue that I've been adding to the content draft doc: https://docs.google.com/a/mozilla.com/document/d/1tuT5fx0cvNuHiUGXfDi07amW58yG57_DF84_MxGkZyI/edit?usp=sharing

Nothing final but it should help with the sketches.

**Comment by sinker** [comment]
awsm thanks! working on templatizing right now.

**Comment by sinker** [comment]
> The blurb in the header may need a box behind it with like 20-30% opacity to make the text more readable, but maybe note

My god, I fixed this with... shudder... a drop shadow. But it works.

**Comment by sinker** [comment]
> The sponsors section feels like it needs a color band or something to set it off from the rest of the page

Yeah, I tried a color band and it felt like TOO MUCH. However, the sponsors section will be display:none until we have sponsors, so nbd.

**Comment by kissane** [comment]
Nice drop shadow, man. 

Sounds like Sponsor bar will still be there, so let's build it out with the Knight and Moz logos and see what it needs.

**Comment by sinker** [comment]
fuckit: 
![sponsordots](https://cloud.githubusercontent.com/assets/361410/6272779/f88f4ae6-b82f-11e4-8d4c-e462e4951186.png)

**Comment by sinker** [comment]
these are all addressed now. closing.
