### ISSUE TITLE
2014 archive created, needs QA

### ISSUE THREAD

**Issue by sinker** [OpenNews/srccon#24]
http://2014.srccon.org/

now works. 

needs some general click-through QA to make sure the subdomain didn't break any links.

**Comment by sinker** [comment]
also, @ryanpitts, we need a strategy for the schedule. I am assuming that schedule.srccon.org will be our SOP for whatever the *current* schedule is, so we'll need to point 2014schedule.srccon.org or something similar to the old one. Do you want to dupe the repo or do some other thing so that there's a separate entity for the old schedule and then I can set up the CNAME record on the DNS side?

**Comment by sinker** [comment]
also, obviously, once we have a new subdomain for the old schedule, we will need to update links to the schedule on this archive site accordingly.

**Comment by kissane** [comment]
Links all seem fine/unbroken.

**Comment by sinker** [comment]
archive is ready to go. closing.
