### ISSUE TITLE
remove sponsorbox before launching

### ISSUE THREAD

**Issue by sinker** [OpenNews/srccon#33]
I am putting this here because I am 100% going to forget otherwise.

**Comment by sinker** [comment]
actually, re-thinking this. We should launch with the Knight & Mozilla logos, and probably a call-out to a VERY BASIC sponsors page that basically is an email link to let us know you're interested.

What do you think @kissane?

**Comment by kissane** [comment]
Yeeeeeeaaaaah I guess we should. I get nervous about more pages, but this is useful. Copy could be something like:

Last year, our sponsors helped us offer scholarships, underwrite coffee-hacking stations, bring live transcription to SRCCON, and more. Stay tuned for a detailed breakdown of sponsorship opportunities for SRCCON 2015, or send us a note if you have questions in the interim.

**Comment by sinker** [comment]
OK, cool. I'm going to try a little more copy, just so the page isn't so stumpy.

**Comment by kissane** [comment]
no stumps

**Comment by sinker** [comment]
SRCCON sponsors help us keep our event cost low, help bring people to the event, and help with the special touches that make SRCCON SRCCON.

Last year, our sponsors helped us offer scholarships, underwrote our coffee-hacking stations, brought live transcription to SRCCON, and more. This year, we'll have even more opportunities for support.

Stay tuned for a detailed breakdown of sponsorship opportunities for SRCCON 2015, or [send us a note](mailto:dan@mozillafoundation.org) if you have questions in the interim.

**Comment by ryanpitts** [comment]
stump is a page that thinks it's fly, also known as a buster

**Comment by kissane** [comment]
Suggest wee tweak to the 1st sentence for parallel construction:

SRCCON sponsors help us keep our event cost low, get people to the event, and bring in the special touches that make SRCCON SRCCON.

**Comment by kissane** [comment]
a stump is a page that can't get no love from me

**Comment by sinker** [comment]
this is fixed, addressed and closing.
