### ISSUE TITLE
introduced a css mystery

### ISSUE THREAD

**Issue by sinker** [OpenNews/srccon#35]
@ryanpitts for some reason in moving from the stand-alone test pages to the template pages, something happened that makes the nav push the h3 text on the homepage down to two lines--it's like it has a force shield around it, and it will not let that h3 pass. 

Anyway, I've messed around wtih this a bunch and am cross-eyed. wondering if you can give it a look.

Old page, everything is right: http://srccon.org/testing/homepage.html
New page, everything is weird: http://srccon.org/testing/

**Comment by ryanpitts** [comment]
On the test page, there are two CSS rules that don't seem to be in place on the new page:

```
header #headbox { clear: both; }
img.makethelogobigger { top: -50px; } /* instead of top: 20px; */
```

Should fix it.
