### ISSUE TITLE
Let's assign photos to pages!

### ISSUE THREAD

**Issue by sinker** [OpenNews/srccon#36]
So we have four pages right now, they need four photos. @kissane and I have been collecting photos in #21, but I want a separate issue for actually deciding what photos go with what things. 

Specifically, right now we have *a lot* of "beautiful MPLS" photos, a few of the celing of the McNamara center, but *no* SRCCON specific photos.

**Comment by sinker** [comment]
So here's either links or thoughts:

* Homepage: https://www.flickr.com/photos/onepointfour/15434041227/sizes/l
* Location: https://www.flickr.com/photos/dannylankford/3616140995
* Sessions: Should really be a session shot, either from SRCCON (ideally) or MozFest. 
* Registration: Fuck if I know.

**Comment by kissane** [comment]
Things that might work for stuff:

![srccon_welcome_crop](https://cloud.githubusercontent.com/assets/1910034/6269592/4581d91c-b822-11e4-8acd-32f39f3c0430.jpg)
![srccon_welcome](https://cloud.githubusercontent.com/assets/1910034/6269589/45813b74-b822-11e4-8919-902c579f0228.jpg)
![srccon_jeremy_presents](https://cloud.githubusercontent.com/assets/1910034/6269590/45815cee-b822-11e4-98ae-97e60ce87677.jpg)
![dsc07663](https://cloud.githubusercontent.com/assets/1910034/6269591/4581a1cc-b822-11e4-9e74-c6d3930dfe9e.JPG)
![dsc07639](https://cloud.githubusercontent.com/assets/1910034/6269594/458340f4-b822-11e4-8dc1-aef7c21d5164.JPG)
![img_6328](https://cloud.githubusercontent.com/assets/1910034/6269593/4582a630-b822-11e4-845d-b0da743124c3.JPG)

**Comment by kissane** [comment]
None of the above things are just right, for various reasons, but they're what we have. Also Jeff Larson's back is weirdly recognizable.

**Comment by ryanpitts** [comment]
I actually like that frosted glass photo a lot

**Comment by sinker** [comment]
OK, we've assigned photos to pages. Closing.
