### ISSUE TITLE
QA the footer

### ISSUE THREAD

**Issue by sinker** [OpenNews/srccon#37]
I'm going to flag @kissane on this, but the footer is now broken up into manageable sub-sections. All of them probably need some eyes, as they're currently just straight pulls from last year's footer:

info column: https://github.com/OpenNews/srccon/blob/gh-pages/_includes/footer_info.html
about srccon column: https://github.com/OpenNews/srccon/blob/gh-pages/_includes/footer_srccon.html
about opennews column:  https://github.com/OpenNews/srccon/blob/gh-pages/_includes/footer_opennews.html

**Comment by kissane** [comment]
Info column:

* type needs tweaking. 
![screen shot 2015-02-19 at 10 41 15 am](https://cloud.githubusercontent.com/assets/1910034/6269835/df8e63bc-b823-11e4-9682-c0a7f841f8dc.png)

* Contact email should now be srccon@opennews.org
* Hide sponsor link?

**Comment by sinker** [comment]
yeah, type is a known css migration issue. 

see my question about sponsors in #33

**Comment by kissane** [comment]
About SRCCON column needs copy update:

SRCCON is a conference for developers, interactive designers, and other people who love to code in and near newsrooms. Join us in Minneapolis June 25 and 26 for two days of peer-to-peer sessions built around conversation and collaboration.

**Comment by sinker** [comment]
OH: we don't currently have code of conduct in our launch pages.

**Comment by kissane** [comment]
OpenNews column could be trued up to match our new blurb:

Knight-Mozilla OpenNews is a joint project of Mozilla and the Knight Foundation that supports the growing community of news developers, designers, and data reporters helping journalism thrive on the open web. More at opennews.org.

**Comment by kissane** [comment]
Code of conduct has to be there. I'm working on tweaks, but for now, please let's pull the old one.

**Comment by sinker** [comment]
OK great. just wasn't on the list in #20

**Comment by kissane** [comment]
Yup, my fault.

**Comment by sinker** [comment]
OK, for any pages like conduct, or sponsors, which won't have a photo top, I have a nice orange dot pattern. However, they will still need 2 sentence subheads so things don't look *too* weird.

**Comment by sinker** [comment]
OK, footer is updated and styles are fixed. Closing.
