### ISSUE TITLE
photo caption has ended me

### ISSUE THREAD

**Issue by sinker** [OpenNews/srccon#39]
so the photo caption that can be viewed on the homepage and the sessions page is being addressed by two separate CSS calls, because it jumps around. I thought this was a homepage-only issue, so I locked down that CSS and the sessions page css separtely, but it turns out, it jumps on every page. It's slaved, apparently, to the size of the box with the h3 & h4. There *has* to be a one-ring approach to this. @ryanpitts, I ask your assistance.

homepage: http://srccon.org/testing/
sessions: http://srccon.org/testing/sessions
screwup on registration: http://srccon.org/testing/registration/

**Comment by sinker** [comment]
I just killed the registration page. 

is now at: http://srccon.org/testing/tickets/

**Comment by ryanpitts** [comment]
just for clarity here, the goal is to have the photo caption basically attached to a locked position at the bottom of the photo (with some bottom-padding, of course), right?

**Comment by sinker** [comment]
yes, I would love for all the captions to be in the position the caption is on the homepage: http://srccon.org/testing/

Also: I say caption but I mean byline.
