### ISSUE TITLE
need a final order for 3 main pages

### ISSUE THREAD

**Issue by sinker** [OpenNews/srccon#42]
currently the lineup in the nav is (from L to R):
tickets
session
location

and the lineup on the home page (from top to bottom ) is:
Location
Registration
Sessions

So in addition to changing the wording to tickets on the home page, we should *probably* have those orders be the same, right?

And, should have some intentionality on the final order of the nav as well.

**Comment by kissane** [comment]
I think the right order is 

Tickets
Sessions
Location

everywhere.

**Comment by ryanpitts** [comment]
Agreed, especially since the homepage banner greets you with a nice big “Minneapolis"

**Comment by sinker** [comment]
#55 closes.
