### ISSUE TITLE
Homepage QA

### ISSUE THREAD

**Issue by kissane** [OpenNews/srccon#43]
* I am trying to nail down the first line, which is killing me like always. Once I get that I will need to adjust the main paragraph accordingly.
* The photos and subheds below the main paragraph should be links to the appropriate pages.
* New copy for the blurbs is in the doc.

More TK.

**Comment by erikao** [comment]
the first line could use a "that" 
"SRCCON returns for another two days of participatory sessions centered on the technical, ethical, design, and editorial challenges *that* newsroom data and apps teams encounter every day."

but could probably be streamlined further. maybe collapse/remove "another two days of"? 

i like that it puts the list of session topic areas front and center.

**Comment by sinker** [comment]
the photos & subheads for the 3 bits below the opening paragraph have been updated & are now active links to the pages (though, currently, those links link to the old version of the pages with those names due to the /testing trickery we're doing right now)

new blurb copy is in place

**Comment by sinker** [comment]
closed.
