### ISSUE TITLE
Remaining photos

### ISSUE THREAD

**Issue by kissane** [OpenNews/srccon#47]
Code of Conduct, maybe a zoom/crop from this? https://www.flickr.com/photos/dvortygirl/3982230988 or this https://www.flickr.com/photos/rebecca_m/3889216481 ?

Sponsorship maybe this?

![dsc07625](https://cloud.githubusercontent.com/assets/1910034/6279658/551e4c5c-b872-11e4-812c-6291939155df.JPG)

**Comment by sinker** [comment]
done. closing.
