### ISSUE TITLE
Bullet weirdness

### ISSUE THREAD

**Issue by kissane** [OpenNews/srccon#50]
The bullets in Code of Conduct have some kind of weird scaling artifacts for me. 

![screen shot 2015-02-19 at 8 32 25 pm](https://cloud.githubusercontent.com/assets/1910034/6280069/72d447d4-b876-11e4-95dc-fc145c4346f3.png)

**Comment by kissane** [comment]
(I think also maybe they should be slightly smaller, relative to the text, but whatevs.)

**Comment by sinker** [comment]
@kissane this was addressed in #51 can you confirm that it doesn't look as janky?

**Comment by kissane** [comment]
@sinker Way less janky, good jorb boss

**Comment by sinker** [comment]
closing.
